version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: shop_user
      POSTGRES_PASSWORD: Vanya2020)
      POSTGRES_DB: shop_db
    ports:
      - "5432:5432"
    networks:
      - shop-net

  product-service:
    build: ./product_service
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://shop_user:Vanya2020)@postgres/shop_db
    networks:
      - shop-net

  order-service:
    build: ./order_service
    ports:
      - "8002:8002"
    depends_on:
      - postgres
      - product-service
    environment:
      DATABASE_URL: postgresql://shop_user:Vanya2020)@postgres/shop_db
      PRODUCT_SERVICE_URL: http://product-service:8001
    networks:
      - shop-net

  auth-service:
    build: ./auth_service
    ports:
      - "8003:8003"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://shop_user:Vanya2020)@postgres/shop_db
      SECRET_KEY: your-super-secret-key-change-me
    networks:
      - shop-net

  gateway:
    build: ./gateway
    ports:
      - "80:80"
    depends_on:
      - product-service
      - order-service
      - auth-service
    networks:
      - shop-net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - shop-net

  admin-frontend:
    build: ./admin_frontend
    ports:
      - "3001:3000"
    networks:
      - shop-net

networks:
  shop-net:
    driver: bridge
